tempo = int(input('Quantos anos tem seu carro? '))  # Atribui à variável "tempo" o valor de um número inteiro
if tempo <= 3:  # Se a variável "tempo" receber um valor igual ou menor do que 3...
    print('Carro novo!')  # Exibe "Carro novo!"
else:  # Senão...
    print('Carro velho!')  # Exibe "Carro velho!"
print('--- FIM ---')  # Exibe "--- FIM ---" independemente do resultado da condição acima
